server:
  port: ${API_GATEWAY_PORT:9000}
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
#      default-filters:
#        - dedupeResponceHeader=Acess-Control-Allow-Credentials Acess-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true