server:
  port: 8083
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/foodieappdb}
  application:
    name: customer-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
#      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
