FROM openjdk
WORKDIR usr/lib
ADD ./target/SpringCloudApiGateway-0.0.1-SNAPSHOT.jar /usr/lib/SpringCloudApiGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","SpringCloudApiGateway-0.0.1-SNAPSHOT.jar"]